name: disney
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  async: ^2.12.0
  flutter:
    sdk: flutter
  go_router: ^14.8.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/primal-survivor/
    - assets/images/goofy-movie/
    - assets/images/incredibles-2/
    - assets/images/lion-king/
    - assets/images/peter-pan/
    - assets/images/tarzan/
    - assets/images/avatar/
    - assets/images/davy-crocket/
    - assets/images/haunted-mansion/
    - assets/images/knight-and-day/
    - assets/images/pirates-of-the-caribbean/
    - assets/images/aliens-of-the-deep/
    - assets/images/drain-the-oceans/
    - assets/images/hostile-planet/
    - assets/images/wild-yellowstone/
    - assets/images/atlantis-rising/




